Initial Commit
HacktheHill/2023.hackthehill.com pull request #128
Opened 2023-05-26 02:22 UTC by Zackydout101

First changes

2023-06-10 02:51 UTC, arcanistzed commented
Please provide a proper PR title using the Conventional Commits specification as described in our [Contributing docs](https://github.com/HacktheHill/.github/blob/main/CONTRIBUTING.md). I'm not able to see which issue this relates to without viewing the code.
I have also linked this PR with the corresponding GitHub issue using the "Development" section in the right sidebar. This is useful because it will automatically close the issue when this PR is merged and it provides a link between the PR and the issue.

2023-06-10 02:57 UTC, arcanistzed requested changes

2023-06-10 02:57 UTC, arcanistzed commented on src/components/Footer/Footer.module.css
> -.footer {
Why are we removing these spaces? That doesn't align with our code formatting configuration.

2023-06-10 02:57 UTC, arcanistzed commented on src/components/Collaborators/MountainFlags.jsx
> -	return <div ref={mountain} className="mountain-flags"></div>;
don't change the class name to camelCase

2023-06-10 02:57 UTC, arcanistzed commented on src/components/Collaborators/Collaborators.module.css
> -.mountain-flags svg {
don't change the class name to camelCase

2023-06-10 02:57 UTC, arcanistzed commented on src/components/Hero/Hero.jsx
> +					<div className={styles["countdow-item"]}>
it says `countdow` not `countdown`

2023-06-10 02:57 UTC, arcanistzed commented on src/components/Hero/Hero.jsx
> +export default Hero;
no need to remove the EOF new line, follow the Prettier code formatting configuration

2023-06-10 02:57 UTC, arcanistzed commented on src/components/Hero/Hero.module.css
> +.countdownItem h3 {
don't use camelCase

2023-07-29 21:16 UTC, arcanistzed requested changes

2023-07-29 21:16 UTC, arcanistzed commented on src/components/Footer/Footer.module.css
> -.footer {
revert these changes to the formatting in this file

2023-07-29 21:16 UTC, arcanistzed commented on src/components/Collaborators/Collaborators.module.css
> -.collaborators {
revert these changes to the formatting in this file

2023-07-29 21:16 UTC, arcanistzed commented on src/components/App/global.css
> -:root {
revert these changes to the formatting in this file

2023-07-29 21:16 UTC, arcanistzed commented on src/components/Hero/Hero.module.css
> -.hero {
revert these changes to the formatting

2023-07-29 21:16 UTC, arcanistzed commented on src/components/Hero/Hero.module.css
> -	color: var(--countdown-item-color);
revert these changes to the formatting

2023-07-29 21:16 UTC, arcanistzed commented on src/components/Notification/Notification.jsx
> -			<div className="notification-content">
revert these changes to the formatting

2023-07-29 21:16 UTC, arcanistzed commented on src/components/Notification/Notification.module.css
> -.notification-content {
revert these changes to the formatting

2023-07-29 21:16 UTC, arcanistzed commented on src/components/Register/Register.module.css
> +* {
we don't need this file??

2023-07-29 21:16 UTC, arcanistzed commented on src/components/Sponsors/Sponsors.module.css
> -.sponsors-row {
revert these changes to the formatting

2023-07-29 21:16 UTC, arcanistzed commented on src/components/Schedule/Schedule.module.css
> -.schedule-title {
revert these changes to the formatting in this file

2023-07-30 13:56 UTC, xsachax commented
should be good to merge, could use a last look-over

2023-07-31 04:01 UTC, arcanistzed requested changes

2023-07-31 04:01 UTC, arcanistzed commented on src/components/Sponsors/Sponsors.jsx
> +				<div className={styles["sponsors-col"]}>
name should be `sponsor-icons`

2023-07-31 04:01 UTC, arcanistzed commented on src/components/Sponsors/Sponsors.jsx
> +						<div key={i} className={styles["sponsors-row"]}>
should be `sponsor-icons-row`

2023-07-31 04:01 UTC, arcanistzed commented on src/components/Sponsors/Sponsors.jsx
> +									className={styles["sponsors-icon-box"]}
should be `sponsor-icon-box`

2023-07-31 04:01 UTC, arcanistzed commented on src/components/Sponsors/Sponsors.jsx
> -			<section id="community" className="sponsors">
shouldn't be removed

2023-08-14 06:39 UTC, arcanistzed approved these changes

2023-08-14 06:39 UTC, merged