Faq fix
HacktheHill/2023.hackthehill.com pull request #135
Opened 2023-08-13 01:07 UTC by Zackydout101

Fixed styling and removed mui

2023-08-14 09:01 UTC, arcanistzed requested changes
There should be an icon for each item that changes from a `+` to a `-`. Perhaps a cool transition would be to have one of the lines fade while the other rotates 90 degrees, with similar code to the hamburger menu.

There should also be an animation for the expansion and contraction, rather than have it be instant.

2023-08-16 19:50 UTC, Zackydout101 commented on src/components/FAQ/FAQ.module.css
>  	font-family: Coolvetica;
In the old code we use this .header {
	font-family: Coolvetica; we don't use a css variable font

2023-08-16 22:22 UTC, arcanistzed commented on src/components/FAQ/FAQ.module.css
>  	font-family: Coolvetica;
Yeah, there are still quite a few places that use that. We need to be consistent though. Some of the fonts use CSS variables. Probably a good idea to make another PR which switches them to all be the same.

2023-08-21 16:06 UTC, arcanistzed commented
Is it possible to make it animate when it's collapsed and when it expands after the first time?

2023-08-21 16:16 UTC, arcanistzed commented
I would recommend using the `<details>` and `<summary>` HTML elements for accessibility

2024-03-17 23:12 UTC, closed without merging